# Generated by Django 4.1.3 on 2023-01-09 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Staff_Name', models.CharField(max_length=200)),
                ('Staff_Position', models.CharField(max_length=200)),
                ('Staff_pic', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Staff_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook', models.URLField(verbose_name='facebook')),
                ('Twitter', models.URLField(verbose_name='Twitter')),
                ('Linkedin', models.URLField(verbose_name='Linkedin')),
                ('Instagram', models.URLField(verbose_name='Instagram')),
                ('Staff_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.team')),
            ],
        ),
    ]
