# Generated by Django 4.1.3 on 2023-01-09 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Staff',
        ),
    ]
