# Generated by Django 4.1.3 on 2023-01-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_alter_staff_staff_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Staff_Pic',
            field=models.FileField(upload_to=''),
        ),
    ]
