# Generated by Django 4.1.3 on 2023-01-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_staff_staff_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Staff_Pic',
            field=models.ImageField(upload_to='team members'),
        ),
    ]
