# Generated by Django 4.1.3 on 2023-01-10 12:11

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0007_alter_staff_staff_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Staff_Pic',
            field=models.ImageField(upload_to=pathlib.PureWindowsPath('C:/Users/LENOVO PC/website/Xarale Telecoms/Xarale/media/team members')),
        ),
    ]
