# Generated by Django 4.1.3 on 2023-01-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_alter_staff_staff_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='Facebook',
            field=models.URLField(blank=True, verbose_name='facebook'),
        ),
        migrations.AddField(
            model_name='staff',
            name='Instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='staff',
            name='Linkedin',
            field=models.URLField(blank=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='staff',
            name='Twitter',
            field=models.URLField(blank=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Staff_Pic',
            field=models.ImageField(upload_to='C:\\Users\\LENOVO PC\\website\\Xarale Telecoms\\Xarale\\media\\team members'),
        ),
        migrations.DeleteModel(
            name='Staff_Social',
        ),
    ]
