# Generated by Django 5.1.3 on 2024-12-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_staff_facebook_staff_instagram_staff_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='Staff_Pic',
            field=models.ImageField(upload_to='C:\\Users\\LENOVO PC\\PROJECTS\\website\\Xarale Telecoms\\Xarale\\media\\team members'),
        ),
    ]
