# Generated by Django 5.1.3 on 2024-12-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='clients/')),
            ],
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Happy Clients', 'Happy Clients'), ('Projects', 'Projects'), ('Hours Of Support', 'Hours Of Support'), ('Hard Workers', 'Hard Workers')], max_length=100)),
                ('icon_class', models.CharField(choices=[('bi bi-emoji-smile', 'bi bi-emoji-smile'), ('bi bi-journal-richtext', 'bi bi-journal-richtext'), ('bi bi-headset', 'bi bi-headset'), ('bi bi-people', 'bi bi-people')], max_length=100)),
                ('value', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
            ],
        ),
    ]
