# Generated by Django 5.1.3 on 2024-12-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_feedback_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='icon_class',
            field=models.CharField(blank=True, choices=[('bi bi-emoji-smile', 'bi bi-emoji-smile'), ('bi bi-journal-richtext', 'bi bi-journal-richtext'), ('bi bi-headset', 'bi bi-headset'), ('bi bi-people', 'bi bi-people')], max_length=100),
        ),
    ]
